import { makeStyles, Theme } from '@material-ui/core/styles';

export const useUserProfilePopupStyles = makeStyles((theme: Theme) => ({
  popoverContainer: {
    width: 320,
    borderRadius: theme.spacing(1),
    overflow: 'visible',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12)',
    position: 'relative',
    marginLeft: theme.spacing(0.5),
    maxHeight: 'none',
    height: 'auto',
  },
  arrow: {
    position: 'absolute',
    left: -18,
    bottom: '10px',
    width: 0,
    height: 0,
    borderTop: '18px solid transparent',
    borderBottom: '18px solid transparent',
    borderRight: '18px solid #ffffff',
    zIndex: 10,
    filter: 'drop-shadow(-2px 0px 4px rgba(0,0,0,0.15))',
  },
  arrowBorder: {
    position: 'absolute',
    left: -20,
    bottom: '78px',
    width: 0,
    height: 0,
    borderTop: '20px solid transparent',
    borderBottom: '20px solid transparent',
    borderRight: '20px solid rgba(0,0,0,0.1)',
    zIndex: 9,
  },
  header: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    padding: theme.spacing(3),
    color: 'white',
    display: 'flex',
    alignItems: 'flex-start',
    gap: theme.spacing(2),
    minHeight: 'auto',
  },
  headerContent: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    wordBreak: 'break-word',
  },
  content: {
    padding: theme.spacing(2),
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1),
  },
  userAvatar: {
    width: 64,
    height: 64,
    fontSize: '1.5rem',
    fontWeight: 600,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    color: 'white',
    flexShrink: 0,
  },
  sidebarAvatar: {
    width: 25,
    height: 25,
    fontSize: '12px',
    fontWeight: 600,
    color: 'white',
    flexShrink: 0,
  },
  userName: {
    fontSize: '1.1rem',
    fontWeight: 600,
    marginBottom: theme.spacing(0.5),
    wordWrap: 'break-word',
    wordBreak: 'break-word',
    lineHeight: 1.3,
    hyphens: 'auto',
  },
  userEmailPopover: {
    fontSize: '0.875rem',
    opacity: 0.9,
    wordWrap: 'break-word',
    wordBreak: 'break-word',
    lineHeight: 1.2,
    hyphens: 'auto',
  },
  menuItem: {
    width: '100%',
    padding: theme.spacing(1.5, 2),
    textAlign: 'left',
    borderRadius: theme.spacing(0.5),
    marginBottom: theme.spacing(1),
    '&:hover': {
      backgroundColor: theme.palette.grey[50],
    },
  },
  signOutButton: {
    width: '100%',
    padding: theme.spacing(1.5),
    color: '#e53e3e',
    fontWeight: 500,
    textTransform: 'none',
    justifyContent: 'flex-start',
    marginTop: theme.spacing(1),
    borderRadius: theme.spacing(0.5),
    '&:hover': {
      backgroundColor: '#fed7d7',
    },
  },
  sidebarItemContent: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    cursor: 'pointer',
    padding: theme.spacing(1.5, 2),
    borderRadius: theme.spacing(0.5),
    margin: theme.spacing(0),
    width: '100%',
    minHeight: '48px',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
  },
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    minWidth: 0,
    flex: 1,
  },
  displayName: {
    fontSize: '0.875rem',
    fontWeight: 500,
    color: theme.palette.common.white,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '150px',
  },
  userEmail: {
    fontSize: '0.75rem',
    color: 'rgba(255, 255, 255, 0.7)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
})); 