import { makeStyles, Theme } from '@material-ui/core';

export const useArtifactoryCatalogTabStyles = makeStyles((theme: Theme) => ({
  root: {
    padding: theme.spacing(3),
  },
  searchAndFilters: {
    marginBottom: theme.spacing(3),
    padding: theme.spacing(2),
    backgroundColor: theme.palette.background.paper,
    borderRadius: theme.shape.borderRadius,
    border: `1px solid ${theme.palette.divider}`,
  },
  searchBar: {
    marginBottom: theme.spacing(2),
  },
  filterRow: {
    display: 'flex',
    gap: theme.spacing(2),
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  filterControl: {
    minWidth: 150,
  },
  viewToggle: {
    marginLeft: 'auto',
  },
  artifactCard: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    border: `1px solid ${theme.palette.divider}`,
    borderRadius: theme.spacing(1),
  },
  listCard: {
    display: 'flex',
    alignItems: 'center',
    padding: theme.spacing(2),
    marginBottom: theme.spacing(1),
  },
  cardContent: {
    flexGrow: 1,
    paddingBottom: theme.spacing(1),
  },
  cardActions: {
    padding: theme.spacing(2),
    paddingTop: theme.spacing(1),
    backgroundColor: theme.palette.background.default,
    borderTop: `1px solid ${theme.palette.divider}`,
    borderRadius: `0 0 ${theme.spacing(1)}px ${theme.spacing(1)}px`,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  artifactName: {
    fontWeight: 600,
    marginBottom: theme.spacing(1),
    color: theme.palette.primary.main,
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
  },
  artifactPath: {
    fontFamily: 'monospace',
    fontSize: '0.75rem',
    color: theme.palette.text.secondary,
    marginBottom: theme.spacing(1.5),
    wordBreak: 'break-all',
    backgroundColor: theme.palette.action.hover,
    padding: theme.spacing(0.75, 1),
    borderRadius: theme.spacing(0.75),
    lineHeight: 1.4,
    maxHeight: '3.2em',
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    border: `1px solid ${theme.palette.divider}`,
    '&:hover': {
      backgroundColor: theme.palette.action.selected,
    },
  },
  metadataRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: theme.spacing(1),
    '& svg': {
      marginRight: theme.spacing(1),
      fontSize: '1.1rem',
      color: theme.palette.text.secondary,
      flexShrink: 0,
    },
  },
  sizeChip: {
    backgroundColor: theme.palette.success.light,
    color: theme.palette.success.contrastText,
    fontWeight: 600,
    fontSize: '0.75rem',
    height: 28,
  },
  repoChip: {
    backgroundColor: theme.palette.primary.light,
    color: theme.palette.primary.contrastText,
    fontWeight: 600,
    fontSize: '0.75rem',
    height: 28,
  },
  url: {
    fontSize: '0.875rem',
    textDecoration: 'none',
    color: theme.palette.secondary.main,
    fontWeight: 600,
    padding: theme.spacing(0.5, 1),
    borderRadius: theme.spacing(0.5),
    border: `1px solid ${theme.palette.secondary.light}`,
    backgroundColor: theme.palette.secondary.light + '20',
    transition: 'all 0.2s ease-in-out',
    '&:hover': {
      backgroundColor: theme.palette.secondary.light + '40',
      borderColor: theme.palette.secondary.main,
    },
  },
  statsContainer: {
    marginBottom: theme.spacing(3),
  },
  statCard: {
    textAlign: 'center',
    padding: theme.spacing(3),
    background: `linear-gradient(135deg, ${theme.palette.primary.light}15, ${theme.palette.secondary.light}15)`,
    borderRadius: theme.spacing(2),
    border: `1px solid ${theme.palette.divider}`,
  },
  statValue: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    background: `linear-gradient(45deg, ${theme.palette.primary.main}, ${theme.palette.secondary.main})`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  statLabel: {
    color: theme.palette.text.secondary,
    fontSize: '0.875rem',
    fontWeight: 500,
    marginTop: theme.spacing(0.5),
  },
  pagination: {
    marginTop: theme.spacing(3),
    display: 'flex',
    justifyContent: 'center',
  },
  noResults: {
    textAlign: 'center',
    padding: theme.spacing(4),
    color: theme.palette.text.secondary,
  },
  listContent: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    gap: theme.spacing(2),
  },
  listMetadata: {
    display: 'flex',
    gap: theme.spacing(1),
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  listPath: {
    fontFamily: 'monospace',
    fontSize: '0.75rem',
    color: theme.palette.text.secondary,
    backgroundColor: theme.palette.action.hover,
    padding: theme.spacing(0.25, 0.75),
    borderRadius: theme.spacing(0.5),
    border: `1px solid ${theme.palette.divider}`,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '300px',
    display: 'inline-block',
  },
  // Skeleton styles
  skeletonCard: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    border: `1px solid ${theme.palette.divider}`,
    borderRadius: theme.spacing(1),
    padding: theme.spacing(2),
  },
  skeletonContent: {
    flexGrow: 1,
  },
  skeletonPath: {
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(2),
  },
  skeletonChips: {
    display: 'flex',
    gap: theme.spacing(1),
    marginBottom: theme.spacing(1),
  },
  skeletonListCard: {
    display: 'flex',
    alignItems: 'center',
    padding: theme.spacing(2),
    marginBottom: theme.spacing(1),
    border: `1px solid ${theme.palette.divider}`,
    borderRadius: theme.spacing(0.5),
  },
  skeletonListContent: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    gap: theme.spacing(2),
  },
  skeletonListMetadata: {
    display: 'flex',
    gap: theme.spacing(1),
    alignItems: 'center',
  },
})); 